### PR TITLE
ConvertNumberStringToInteger

### PR DESCRIPTION
**Pull request by ihccik**
buggy default solution fixed
id added to file name
task name updated with a meaningful one
alternate solution added
new package created
examples added
detailed explanation url added
google sheet updated

### CODE REVIEW

**Review by Cemil5 — CHANGES_REQUESTED** [review]
should class name be "id7_ConvertNumberStringToIntegerWithoutWrappers" ?
first method "forLoop" ?
second method "forEachLoop"

**Comment by ihccik** [comment]
@Cemil5 
requested changes reflected
sheet updated

**Review by Cemil5 — APPROVED** [review]
perfect

**Review by Cemil5 — APPROVED** [review]
perfect

**Review by Cemil5 — APPROVED** [review]

**Review by Cemil5 — APPROVED** [review]

**Review by Cemil5 — APPROVED** [review]

**Review by Cemil5 — APPROVED** [review]

**Pull request merged**
